---
- hosts: 127.0.0.1
  become: true
  connection: local
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
    - name: Update apt and install required system packages
      apt:
        pkg:
          - curl
          - vim
          - git
          - htop
          - iotop
          - python3-pip
          - pipenv
          - ack
        state: latest
        update_cache: true
    - name: Remove snap apps
      become: true
      command: "snap remove chromium firefox cups gnome-42-2204 core22 gtk-common-themes"

    - name: Remove snap bare
      become: true
      command: "snap remove bare && snap remove snapd && sudo apt remove -y snapd"

    - name: Install firefox with mozilla repo
      become: true
      command: "bash scripts/install-firefox.sh"

    - name: Install Obsidian
      package:
        deb: deb/obsidian_1.7.4_amd64.deb
